#ifndef __LIMITATIONS_H__
#define __LIMITATIONS_H__

#define PID_MAX_LENGTH 30
#define MAX_NAME_LENGTH 25
#define MAX_PASSWORD_LENGTH 25
#define MAX_GROUP_NAME_SIZE 25
#define HASH_SIZE_GROUPS (20)
#define MAX_BUFFER_LENGTH 255
#define MAX_ACTIVE_GROUP_NUMBER 100

#endif /* __LIMITATIONS_H__ */